# Generated by Django 4.2.5 on 2024-01-12 21:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Rostr", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="position",
            field=models.CharField(
                choices=[("Non-Admin", "Non-Admin"), ("Admin", "Admin")],
                default="Non-Admin",
                max_length=64,
            ),
        ),
    ]
