# Generated by Django 4.2.5 on 2024-01-16 20:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("Rostr", "0002_alter_user_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="shift",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="shift",
            name="end",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="shift",
            name="start",
            field=models.TimeField(),
        ),
    ]
