# Generated by Django 5.0.2 on 2024-03-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Rostr", "0005_alter_shift_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shift",
            name="end",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="shift",
            name="start",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
