# Generated by Django 5.0.2 on 2024-03-07 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Rostr", "0006_alter_shift_end_alter_shift_start"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="position",
        ),
        migrations.AddField(
            model_name="user",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
    ]
